# fly.toml app configuration file generated for tinybase-crsqlite-spring-fire-444 on 2024-09-01T21:22:52+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tinybase-crsqlite-spring-fire-444'
primary_region = 'sin'

[build]

[env]
  DB_PATH = '/app/data/dbs'

[[mounts]]
  source = 'tiny_data'
  destination = '/app/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = [ 'app' ]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
